goview/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
from django.conf.urls import include

from goview import views

urlpatterns = patterns('',
	# Admin
	url(r'^admin/?', include(admin.site.urls)),
	# Base HTML views
	url(r'^$', views.index, name='index'),
	url(r'^(?P<project_id>[0-9]+)/?$', views.project, name='project'),
	url(r'^project/(?P<project_id>[a-zA-Z_\-0-9]+)/?$', views.project, name='project'),
  # Commands
	url(r'^update/(?P<project_id>[a-zA-Z_\-0-9]+)/?$', views.update, name='update'),
	url(r'^update/?$', views.update_all, name='update_all'),
	# Graph service
	url(r'^graph/?(?P<type>([amtc]|(added)|(modified)|(total)|(cpc)))?/commit/(?P<project_id>[a-zA-Z_\-0-9]+)/(?P<commit1>[0-9a-z]{4,40})(?:/(?P<commit2>[0-9a-z]{4,40}))?/graph.svg$', views.graph_commit, name='graph_commit'),
	url(r'^graph/?(?P<type>([amtc]|(added)|(modified)|(total)|(cpc)))?/depth/(?P<project_id>[a-zA-Z_\-0-9]+)/(?P<depth>[0-9]+)(?:/(?P<from_commit>[0-9a-z]{4,40}))?/graph.svg$', views.graph_depth, name='graph_depth'),
	url(r'^graph/?(?P<type>([amtc]|(added)|(modified)|(total)|(cpc)))?/date/(?P<project_id>[a-zA-Z_\-0-9]+)/(?P<date1>[0-9\-]+)(?:/(?P<date2>[0-9\-]+)?)/graph.svg$', views.graph_date, name='graph_date'),
	url(r'^graph/dependency/(?P<project_id>[a-zA-Z_\-0-9]+)/graph.png$', views.graph_dependency, name='graph_dependency'),
	# REST service
	url(r'^rest/list/$', views.rest_list, name='rest_list'),
	url(r'^rest/info/(?P<project_id>[a-zA-Z_\-0-9]+)/$', views.rest_info, name='rest_info'),
	url(r'^rest/commit/(?P<project_id>[a-zA-Z_\-0-9]+)/(?P<commit1>[0-9a-z]{4,40})(?:/(?P<commit2>[0-9a-z]{4,40}))?/?$', views.rest_commit, name='rest_commit'),
	url(r'^rest/depth/(?P<project_id>[a-zA-Z_\-0-9]+)/(?P<depth>[0-9]+)(?:/(?P<from_commit>[0-9a-z]{4,40}))?/?$', views.rest_depth, name='rest_depth'),
	url(r'^rest/date/(?P<project_id>[a-zA-Z_\-0-9]+)/(?P<date1>[0-9\-]+)(?:/?P<date2>[0-9\-]*)?/?$', views.rest_date, name='rest_date'),
	url(r'^rest/check-deps/(?P<project_id>[a-zA-Z_\-0-9]+)/(?P<commit>[0-9a-z]{4,40})/?$', views.rest_check_deps, name='rest_check_deps'),
	url(r'^rest/fedora-pkgdb/(?P<package>[a-zA-Z_\-0-9]+)/?$', views.rest_fedora_pkgdb, name='rest_fedora_pkgdb'),
	# Build in pages
	url(r'^review/?$', views.review, name='review'),
	url(r'^request/?$', views.request, name='request'),
	url(r'^godeps-apidiff/?$', views.godeps_apidiff, name='godeps_apidiff'),
	# Generic pages
	url(r'^(?P<page_name>[a-z\-0-9]+)/?$', views.page, name='page'),
)

goweb/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
	url(r'^', include('goview.urls', namespace = "goview")),
	url(r'^admin/', include(admin.site.urls)),
)

goview/models.py
import contextlib
import sys
from django.db import models, connection
from django.utils import formats

class GoProjectReview(models.Model):
	#
	email          = models.CharField(max_length = 200)
	text           = models.TextField()
	date           = models.DateTimeField()
	notes          = models.TextField()
	resolved       = models.BooleanField(default = False)

	class Meta:
		verbose_name = "Go Project Review"
		verbose_name_plural = "Go Project Reviews"

	def __unicode__(self):
		return "{0} - {1}".format(
				formats.date_format(self.date, "SHORT_DATETIME_FORMAT"),
				self.email)

class GoProjectRequest(models.Model):
	#
	email          = models.CharField(max_length = 200)
	scm_url        = models.CharField(max_length = 250)
	text           = models.TextField()
	date           = models.DateTimeField()
	notes          = models.TextField()
	resolved       = models.BooleanField(default = False)

	class Meta:
		verbose_name = "Go Project Request"
		verbose_name_plural = "Go Project Requests"

	def __unicode__(self):
		return self.scm_url

class GoPage(models.Model):
	#
	url_name       = models.CharField(max_length = 250, unique = True)
	name           = models.CharField(max_length = 250)
	content        = models.TextField()

	class Meta:
		verbose_name = "Page"
		verbose_name_plural = "Pages"

	def __unicode__(self):
		return self.name

class GoProjectDesc(models.Model):
	#
	name           = models.CharField(max_length = 250)
	full_name      = models.CharField(max_length = 250, unique = True)
	scm_url        = models.CharField(max_length = 250)
	trend          = models.IntegerField(default = 0)
	update_lock    = models.BooleanField(default = False)
	update_date    = models.DateTimeField(null = True)

	class Meta:
		verbose_name = "Go Project Description"
		verbose_name_plural = "Go Project Descriptions"

	def __unicode__(self):
		return self.full_name

class GoProjectCommit(models.Model):
	project_desc   = models.ForeignKey(GoProjectDesc)
	#
	commit         = models.CharField(max_length = 250)
	tag            = models.CharField(max_length = 250)
	commit_msg     = models.TextField()
	author         = models.CharField(max_length = 250)
	date           = models.DateTimeField()
	changes_count  = models.IntegerField(default = 0)

	class Meta:
		verbose_name = "Go Project Commit"
		verbose_name_plural = "Go Project Commits"

	def __unicode__(self):
		return self.commit[:8]

class GoProjectLog(models.Model):
	project_commit = models.ForeignKey(GoProjectCommit)
	#
	modification   = models.BooleanField(default = False)
	api_change     = models.CharField(max_length = 250)
	package_name   = models.CharField(max_length = 250)

	class Meta:
		verbose_name = "Go Project Log"
		verbose_name_plural = "Go Project Logs"

	def __unicode__(self):
		return "{0}/{1}".format(self.package_name, self.api_change)

@contextlib.contextmanager
def db_lock(tables):
	def lock_tables(tables):
		table_names = [model._meta.db_table for model in tables]
		statement = ', '.join(['%s WRITE' % table for table in table_names])
		statement = 'LOCK TABLES %s' % ', '.join([statement])
		cursor = connection.cursor()
		print >> sys.stderr, "Locking..."
		#cursor.execute(statement)
		return cursor

	if connection.settings_dict['ENGINE'] != 'django.db.backends.mysql':
		raise Exception("Database lock is probably not supported!")

	cursor = lock_tables(tables)
	try:
		yield cursor
	finally:
		print >> sys.stderr, "Unlocking..."
		cursor.execute("UNLOCK TABLES")

goview/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404
from goview.form import GoReviewForm, GoRequestForm
from django.http import HttpResponseRedirect
import json
from goview.project import GoProjectSCMPool, GoProjectSCM, get_fedora_pkgdb_commit
import sys
from goview.models import GoProjectReview, GoProjectRequest, GoPage
from goview.graph import GoGraph
from datetime import datetime
from gomail.mailer import notify_review, notify_request
from django.db import InternalError
from django.conf import settings

# Base HTML views

def index(request):
	pool = GoProjectSCMPool(settings.GOLANG_REPOS)
	return render(request, 'goview/list_projects.html', {'projects': pool.get_all()})

def project(request, project_id):
	pool = GoProjectSCMPool(settings.GOLANG_REPOS)
	project = pool.get_project(project_id)
	if project.update_date:
		project.update_date = project.update_date.strftime('%F %T %z')
	return render(request, 'goview/project.html', {'project': project})

# Commands

def update(request, project_id):
	if request.user.is_authenticated():
		pool = GoProjectSCMPool(settings.GOLANG_REPOS)
		pool.update(project_id)
		return HttpResponse("OK", content_type="text/plain")
	else:
		return HttpResponseForbidden()

def update_all(request):
	if request.user.is_authenticated():
		pool = GoProjectSCMPool(settings.GOLANG_REPOS)
		p = pool.update_all()
		return HttpResponse("OK", content_type="text/plain")
	else:
		return HttpResponseForbidden()

# REST service

def rest_list(request):
	pool = GoProjectSCMPool(settings.GOLANG_REPOS)
	res = pool.get_list()
	return HttpResponse(json.dumps(res), content_type='application/json')

def rest_info(request, project_id):
	pool = GoProjectSCMPool(settings.GOLANG_REPOS)
	res = pool.get_info(project_id)
	# datetime is not serializable for JSON
	res['update'] = res['update'].strftime('%F %T %z') if res['update'] is not None else None
	return HttpResponse(json.dumps(res), content_type='application/json')

def rest_commit(request, project_id, commit1, commit2 = None):
	pool = GoProjectSCMPool(settings.GOLANG_REPOS)
	res = pool.fetch_commit(project_id, commit1, commit2)
	return HttpResponse(json.dumps(res), content_type='application/json')

def rest_depth(request, project_id, depth, from_commit = None):
	pool = GoProjectSCMPool(settings.GOLANG_REPOS)
	res = pool.fetch_depth(project_id, depth, from_commit)
	return HttpResponse(json.dumps(res), content_type='application/json')

def rest_date(request, project_id, date1, date2 = None):
	pool = GoProjectSCMPool(settings.GOLANG_REPOS)
	res = pool.fetch_date(project_id, date1, date2)
	return HttpResponse(json.dumps(res), content_type='application/json')

def rest_check_deps(request, project_id, commit):
	pool = GoProjectSCMPool(settings.GOLANG_REPOS)
	res = pool.check_deps(project_id, commit)
	return HttpResponse(json.dumps(res), content_type='application/json')

def rest_fedora_pkgdb(request, package):
	return HttpResponse(json.dumps(get_fedora_pkgdb_commit(package)), content_type='application/json')

# Graph service

def makeSVG(name, data, type):
	if type == 'a' or type == 'added':
		res = GoGraph.makeSVGAdded(name, data)
	elif type == 'm' or type == 'modified':
		res = GoGraph.makeSVGRemoved(name, data)
	elif type == 't' or type == 'total' or type == None or len(type) == 0:
		res = GoGraph.makeSVGTotal(name, data)
	elif type == 'c' or type == 'cpc':
		res = GoGraph.makeSVGCPC(name, data)
	else:
		raise InternalError("unsupported Graph type")
	return res

def graph_commit(request, project_id, commit1, commit2 = None, type = None):
	pool = GoProjectSCMPool(settings.GOLANG_REPOS)
	com = pool.fetch_commit(project_id, commit1, commit2)
	com.reverse()
	return HttpResponse(makeSVG(pool.get_project(project_id).full_name, com, type), content_type='image/svg+xml')

def graph_depth(request, project_id, depth, from_commit = None, type = None):
	pool = GoProjectSCMPool(settings.GOLANG_REPOS)
	com = pool.fetch_depth(project_id, depth, from_commit)
	com.reverse()
	return HttpResponse(makeSVG(pool.get_project(project_id).full_name, com, type), content_type='image/svg+xml')

def graph_date(request, project_id, date1, date2 = None, type = None):
	pool = GoProjectSCMPool(settings.GOLANG_REPOS)
	com = pool.fetch_date(project_id, date1, date2)
	com.reverse()
	return HttpResponse(makeSVG(pool.get_project(project_id).full_name, com, type), content_type='image/svg+xml')

def graph_dependency(request, project_id):
	pool = GoProjectSCMPool(settings.GOLANG_REPOS)
	return HttpResponse(pool.get_dependnency_graph(project_id), content_type='image/png')

# Requests & Reviews

def request(request):
	if request.method == 'POST':
		form = GoRequestForm(request.POST)
		if form.is_valid():
			go_request = GoProjectRequest()
			go_request.email = request.POST['email']
			go_request.text = request.POST['text']
			go_request.scm_url = request.POST['scm_url']
			go_request.date = datetime.now()
			go_request.save()
			notify_request(go_request)
			return HttpResponseRedirect('/request-added')
	else:
		form = GoRequestForm()
	rev = GoPage.objects.get(url_name__exact='request')
	return render(request, 'goview/request.html', {'page': rev, 'form': form})

def review(request):
	if request.method == 'POST':
		form = GoReviewForm(request.POST)
		if form.is_valid():
			go_review = GoProjectReview()
			go_review.email = request.POST['email']
			go_review.text = request.POST['text']
			go_review.date = datetime.now()
			go_review.save()
			notify_review(go_review)
			return HttpResponseRedirect('/review-added')
	else:
		form = GoReviewForm()
	rev = GoPage.objects.get(url_name__exact='review')
	return render(request, 'goview/review.html', {'page': rev, 'form': form})

def godeps_apidiff(request):
	page = get_object_or_404(GoPage, url_name__exact='godeps-apidiff')
	return render(request, 'goview/godeps_apidiff.html', {'page': page})

# Generic pages

def page(request, page_name):
	page = get_object_or_404(GoPage, url_name__exact=page_name)
	return render(request, 'goview/page.html', {'page': page})

goview/templates/goview/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static "goview/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "goview/css/goweb.css" %}" rel="stylesheet">
    <link href="{% static "goview/css/bootstrap-dialog.css" %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static "goview/img/favicon.png" %}" type="image/x-icon">
    <link rel="icon" href="{% static "goview/img/favicon.png" %}" type="image/x-icon">
    <script src="{% static "goview/js/jquery.min.js" %}"></script>
    <title>{% block html_title %}gofed-web{% endblock html_title %}</title>
  </head>
  <body>
    {% include "goview/menu.html" %}
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
    {% include "goview/footer.html" %}
  </body>
</html>

goview/templates/goview/footer.html
{% load staticfiles %}
    <div class="text-center footer">
      <p class="text-muted">
        &copy; 2015
        <a href="http://github.com/fridex/gofed-web">Source code</a>
      </p>
    </div>
    <script src="{% static "goview/js/bootstrap.min.js" %}"></script>
    <script src="{% static "goview/js/goweb.js" %}"></script>
    <script src="{% static "goview/js/bootstrap-dialog.js" %}"></script>
    <script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
    </script>

goview/templates/goview/godeps_apidiff.html
{% extends "goview/base.html" %}
{% load staticfiles %}

{% block html_title %}gofed-web: {{ page.name }}{% endblock html_title %}

{% block content %}
<h2>{{ page.name }}</h2>

<div id="godeps_json_input" class="hidden">
{% autoescape off %}
{{ page.content }}
{% endautoescape %}
  <div>
    <div class="form-group">
      <label for="id_text">Godeps.json</label>
      <textarea class="form-control" cols="40" id="godeps_json" name="text" rows="8"></textarea>
    </div>
    <button id="godeps_json_submit" type="submit" class="btn btn-primary pull-right">
      <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
      Submit
    </button>
  </div>
  <input id="upload_godeps" type="file">
</div>

<div id="godeps_json_table" class="hidden">
  <div class="row vertical-align">
    <div class="col-md-6 hidden-md hidden-xs">
       <img src="{% static "goview/img/goweb-logo.jpg" %}"/>
    </div>

    <div class="col-md-6 hidden-md hidden-xs">
      <dl class="dl-horizontal">
        <dt>GoVersion</dt>
        <dd id="godeps_json_goversion">Unknown</dd>
        <dt>ImportPath</dt>
        <dd id="godeps_json_import_path">Unknown</dd>
        <dt>Packages</dt>
        <dd id="godeps_json_packages">Unknown</dd>
      </dl>
      <span id="load_spinner" style="font-size: 2em;">
        <span class="glyphicon glyphicon-repeat glyphicon-repeat-animate"></span>
      </span>
    </div>
  </div>


  <button id="godeps_json_new_input" type="submit" class="btn btn-primary pull-right">
    <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
    New Godeps.json
  </button>

  <div id="godeps_json_div_deps" class="hidden">
    <h3>Deps APIdiff Stats</h3>
    <table class="table table-striped table-hover" class="">
      <thead>
        <tr>
          <th class="">Package</th>
          <th class="text-center">APIdiff Stats</th>
          <th class="text-center">APIdiff Details</th>
        </tr>
      </thead>
      <tbody id="godeps_json_table_deps">
      </tbody>
    </table>
  </div>

  <div id="godeps_json_div_unresolved" class="hidden">
    <h3>Unresolved Packages</h3>
    <table class="table table-striped table-hover" class="">
      <thead>
        <tr>
          <th class="">Import Path / Package</th>
          <th class="">Reason</th>
        </tr>
      </thead>
      <tbody id="godeps_json_table_unresolved">
      </tbody>
    </table>
  </div>

  <div id="godeps_json_div_errors" class="hidden">
    <h3>Erros</h3>
    <table class="table table-striped table-hover" class="">
      <thead>
        <tr>
          <th class="">Package</th>
          <th class="">Error</th>
        </tr>
      </thead>
      <tbody id="godeps_json_table_errors">
      </tbody>
    </table>
  </div>


</div>

<script type="text/javascript" src="{% static "goview/js/godeps_json_apidiff.js" %}"></script>

{% endblock content %}

goview/templates/goview/index.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />
{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">

{% if app_list %}
    {% for app in app_list %}
        <div class="app-{{ app.app_label }} module">
        <table>
        <caption>
            <a href="{{ app.app_url }}" class="section" title="{% blocktrans with name=app.name %}Models in the {{ name }} application{% endblocktrans %}">
                {% blocktrans with name=app.name %}{{ name }}{% endblocktrans %}
            </a>
        </caption>
        {% for model in app.models %}
            <tr class="model-{{ model.object_name|lower }}">
            {% if model.admin_url %}
                <th scope="row"><a href="{{ model.admin_url }}">{{ model.name }}</a></th>
            {% else %}
                <th scope="row">{{ model.name }}</th>
            {% endif %}

            {% if model.add_url %}
                <td><a href="{{ model.add_url }}" class="addlink">{% trans 'Add' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}

            {% if model.admin_url %}
                <td><a href="{{ model.admin_url }}" class="changelink">{% trans 'Change' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}
            </tr>
        {% endfor %}
        </table>
        </div>
    {% endfor %}
{% else %}
    <p>{% trans "You don't have permission to edit anything." %}</p>
{% endif %}
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>{% trans 'Recent Actions' %}</h2>
        <h3>{% trans 'My Actions' %}</h3>
            {% load log %}
            {% get_admin_log 10 as admin_log for_user user %}
            {% if not admin_log %}
            <p>{% trans 'None available' %}</p>
            {% else %}
            <ul class="actionlist">
            {% for entry in admin_log %}
            <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                {% if entry.is_deletion or not entry.get_admin_url %}
                    {{ entry.object_repr }}
                {% else %}
                    <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
                <br/>
                {% if entry.content_type %}
                    <span class="mini quiet">{% filter capfirst %}{% trans entry.content_type.name %}{% endfilter %}</span>
                {% else %}
                    <span class="mini quiet">{% trans 'Unknown content' %}</span>
                {% endif %}
            </li>
            {% endfor %}
            </ul>
            {% endif %}
    </div>
</div>
{% endblock %}

goview/templates/goview/list_projects.html
{% extends "goview/base.html" %}
{% load staticfiles %}

{% block html_title %}gofed-web: List of Golang repos{% endblock html_title %}

{% block content %}
    <div class="container">
      <div class="row vertical-align">
        <div class="col-md-6">
          <img src="{% static "goview/img/goweb-logo.jpg" %}"/>
        </div>
        <div class="col-md-6 form-group has-feedback input-group">
          <span class="input-group-addon">
            <i class="glyphicon glyphicon-search "></i>
          </span>
          <input type="text" class="form-control" id="search_projects" placeholder="Search projects" autofocus="autofocus" />
        </div>
      </div>
      <table class="table table-striped table-hover" id="project_list" class="">
        <thead>
          <tr>
            <th class="text-center"><a href="#" id="sort_repo">
              <span class="glyphicon glyphicon-education" aria-hidden="true"></span>
            </a></th>
            <th class=""><a href="#" id="sort_project">
              <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true"></span>
              Project
            </a></th>
            <th class="text-center"><a href="#" id="sort_trend">
              <span class="glyphicon glyphicon-sort-by-attributes-alt" aria-hidden="true"></span>
              APIdiff trend
            </a></th>
          </tr>
        </thead>
        <tbody>
          {% for project in projects %}
            <tr>
              {% if 'bitbucket.org' in project.scm_url %}
              <td class="col-md-2 text-center"><a href="{{ project.scm_url }}"><img src="{% static "goview/img/bitbucket-logo.png" %}" width="15px"/></a></td>
              {% else %}
              <td class="col-md-2 text-center"><a href="{{ project.scm_url }}"><img src="{% static "goview/img/github-logo.png" %}" width="15px"/></a></td>
              <!-- TODO: not bitbucket nor github logo -->
              {% endif %}
              <td class="col-md-8"><a href="{% url 'goview:project' project.full_name %}" class="goview-project">{{ project.full_name }}</a></td>
              <td class="col-md-2 text-center">{{ project.trend }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="text-right">
        {% if user.is_authenticated %}
        <button type="button" class="btn btn-default btn-md" id="update_all">
          <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
          Force update all
        </button>
        {% endif %}
      </div>
    </div>
    <script src="{% static "goview/js/goview-list.js" %}"></script>
{% endblock content %}

goview/templates/goview/menu.html
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">gofed-web</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'goview:index' %}">List of Projects</a></li>
            <li><a href="{% url 'goview:request' %}">Add package</a></li>
            <li><a href="{% url 'goview:review' %}">Add review</a></li>
            <li><a href="{% url 'goview:godeps_apidiff' %}">Godeps.json APIdiff</a></li>
            <li><a href="{% url 'goview:page' "documentation" %}">Doc</a></li>
            <li><a href="{% url 'goview:page' "about" %}">About</a></li>
            <li>
              {% if not user.is_authenticated %}
              <a class="text-right" href="/admin/">
                <i class="glyphicon glyphicon-lock"></i>
                Log in
              </a>
              {% else %}
              <a class="text-right" href="/admin/">
                <i class="glyphicon glyphicon-user"></i>
                Admin
              </a>
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>

goview/templates/goview/page.html
{% extends "goview/base.html" %}
{% load staticfiles %}

{% block html_title %}gofed-web: {{ page.name }}{% endblock html_title %}

{% block content %}
<h2>{{ page.name }}</h2>
{% autoescape off %}
{{ page.content }}
{% endautoescape %}
{% endblock content %}

goview/templates/goview/request.html
{% extends "goview/base.html" %}

{% block html_title %}gofed-web: {{ page.name }}{% endblock html_title %}

{% block content %}
      <h2>{{ page.name }}</h2>
      <div>
         {% autoescape off %}
         {{ page.content }}
         {% endautoescape %}
      </div>
      <hr>
      <form action="/request/" method="POST">
        {% csrf_token %}
        {% if error %}
        <div class="alert alert-danger fade in">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <strong>Error: </strong> {{ form.non_field_errors }}
        </div>
        {% endif %}
        {% if form.email.errors %}
        <div class="form-group has-error">
        {% else %}
        <div class="form-group">
        {% endif %}
          <label for="id_email">e-mail</label>
          {{ form.email }}
          <span class="help-block">{{ form.email.errors }}</span>
        </div>
        {% if form.scm_url.errors %}
        <div class="form-group has-error">
        {% else %}
        <div class="form-group">
        {% endif %}
          <label for="id_scm_url">SCM URL</label>
          {{ form.scm_url }}
          <span class="help-block">{{ form.scm_url.errors }}</span>
        </div>
        {% if form.text.errors %}
        <div class="form-group has-error">
        {% else %}
        <div class="form-group">
        {% endif %}
          <label for="id_text">Review request text</label>
          {{ form.text }}
          <span class="help-block">{{ form.text.errors }}</span>
        </div>
        <button type="submit" class="btn btn-primary pull-right">
          <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          Submit
        </button>
      </form>
{% endblock content %}

goview/templates/goview/review.html
{% extends "goview/base.html" %}

{% block html_title %}gofed-web: {{ page.name }}{% endblock html_title %}

{% block content %}
      <h2>{{ page.name }}</h2>
      <div>
         {% autoescape off %}
         {{ page.content }}
         {% endautoescape %}
      </div>
      <hr>
      <form action="/review/" method="POST">
        {% csrf_token %}
        {% if error %}
        <div class="alert alert-danger fade in">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <strong>Error: </strong> {{ form.non_field_errors }}
        </div>
        {% endif %}
        {% if form.email.errors %}
        <div class="form-group has-error">
        {% else %}
        <div class="form-group">
        {% endif %}
          <label for="id_email">e-mail</label>
          {{ form.email }}
          <span class="help-block">{{ form.email.errors }}</span>
        </div>
        {% if form.text.errors %}
        <div class="form-group has-error">
        {% else %}
        <div class="form-group">
        {% endif %}
          <label for="id_text">Review request text</label>
          {{ form.text }}
          <span class="help-block">{{ form.text.errors }}</span>
        </div>
        <button type="submit" class="btn btn-primary pull-right">
          <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          Submit
        </button>
      </form>
{% endblock content %}